### ISSUE TITLE
Cuda OOM in Win10

### ISSUE THREAD

**Issue by piggybox** [facebookresearch/pifuhd#24]
I have a 2080 card with 8G memory but still ran into the following OOM problem.  The env is pytorch 1.5.1 on Win 10. I pretty much closed all other apps when running this.

Error msg:
`CUDA out of memory. Tried to allocate 782.00 MiB (GPU 0; 8.00 GiB total capacity; 4.43 GiB already allocated; 610.25 MiB free; 5.29 GiB reserved in total by PyTorch)`

Any one shred a light on how to make more memory available?

**Comment by trufty** [comment]
Try reducing "num_samples" and "interval" in recon.py from 50,000 to 25,000.  That worked for me.

**Comment by kendrick90** [comment]
I tried this to get it working on a laptop with an rtx2060 6GB and it won't work no matter how small I make the num_samples or interval :(

**Comment by wingdi** [comment]
> I tried this to get it working on a laptop with an rtx2060 6GB and it won't work no matter how small I make the num_samples or interval :(

I have same problems win10/RTX2060 6GB/desktop   , num_samples 、interval 128， still OOM...... do you solve it?

**Comment by kendrick90** [comment]
No seems like it won't run. I don't know enough to go further but I found
you can increase the size from 256 to 400 in the the colab. It shows some
malloc lines but still outputs the file. Don't know if it's a soft crash or
what but it seems to work.
